import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import React, { useEffect, useState } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import CountryCodes from './countrycodes';

export default function Home() {
  const [selectedCountry, setselectedCountry] = useState('+91');
  const [mobileno, setmobileno] = useState('');
  var url = 'https://wa.me/';

  return (
    <div className={styles.container}>
      <Head>
        <title>WhatsAppDM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="PageWrapper container">
        <div className="contentWrapper">
          <p className="Heading display-2">
            WhatsApp
            <a
              href="https://wa.me/918655301910?text=Hey I checked your WhatsappDM Project"
              className="DMText"
            >
              DM
            </a>
          </p>
          <p class="lead mb-5">
            Direct Message on Whatsapp without saving Number
          </p>

          <div className="input-group input-group-lg mb-3">
            <select
              className="form-select countryCodes"
              data-live-search="true"
              aria-label="Default select example"
              onChange={(e) => {
                setselectedCountry(e.target.value);
              }}
            >
              <CountryCodes />
            </select>
            <span class="input-group-text" id="basic-addon1">
              {selectedCountry}
            </span>
          </div>
          <div className="input-group input-group-lg">
            <input
              type="tel"
              aria-label="Mobile No"
              className="form-control form-control-lg mobNo text-center"
              placeholder="Mobile No"
              maxLength={10}
              value={mobileno}
              onChange={(e) => {
                setmobileno(e.target.value);
              }}
            />
          </div>

          <button
            onClick={() => {
              console.log(url + selectedCountry + mobileno + '?text=Hi');
            }}
            class="button-30 mt-3 "
          >
            Say Hi
          </button>
        </div>
      </div>
    </div>
  );
}
